### Test 1: Get all Tasks_status
GET {{host}}/tasks_status
Accept: application/json

### Test 2: Get a Tasks_status by status_id
GET {{host}}/tasks_status/1
Accept: application/json

### Test 3: Post a Tasks_status
POST {{host}}/tasks_status
Accept: application/json
Content-Type: application/json

{
  "status_name": "New status"
}

### Test 4: Post a Tasks_status with status_id(it should give error)
POST {{host}}/tasks_status
Accept: application/json
Content-Type: application/json

{
  "status_id": 5,
  "status_name": "New status"
}

### Test 5: Post a Tasks_status with empty payload{}
POST {{host}}/tasks_status
Accept: application/json
Content-Type: application/json

{
}

###Test 6: Update a Tasks_status by status_id
PUT {{host}}/tasks_status/2
Accept: application/json
Content-Type: application/json

{
   "status_name": "Not important"
}

### Test 7: Update all information with status_id (it should give error)
PUT {{host}}/tasks_status/2
Accept: application/json
Content-Type: application/json

{
  "status_id": 5,
  "status_name": "Updated status"
}

### Test 8: Delete Tasks_status by status_id
DELETE {{host}}/tasks_status/3
Accept: application/json

### Test 9: Delete a non existent Tasks_status
DELETE  {{host}}/tasks_status/555
Accept: application/json

###Test 10: Get all tasks by status_id
GET{{host}}/tasks_status/1/tasks
Accept: application/json

###Test 11: Get all tasks by status_id and sprint_id
GET{{host}}/tasks_status/1/sprints/1/tasks
Accept: application/json